<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Vea" duration-ms="8683805" started-at="2015-04-03T11:04:16Z" finished-at="2015-04-03T13:28:59Z">
    <groups>
    </groups>
    <test name="Vea" duration-ms="8683805" started-at="2015-04-03T11:04:16Z" finished-at="2015-04-03T13:28:59Z">
      <class name="services.vea.VeaBot">
        <test-method status="PASS" signature="openDriver()[pri:0, instance:services.vea.VeaBot@7e78fc6]" name="openDriver" is-config="true" duration-ms="3047" started-at="2015-04-03T08:04:16Z" finished-at="2015-04-03T08:04:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openDriver -->
        <test-method status="PASS" signature="run()[pri:0, instance:services.vea.VeaBot@7e78fc6]" name="run" duration-ms="8680717" started-at="2015-04-03T08:04:19Z" finished-at="2015-04-03T10:28:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run -->
        <test-method status="FAIL" signature="addScreenshot(org.testng.ITestResult)[pri:0, instance:services.vea.VeaBot@7e78fc6]" name="addScreenshot" is-config="true" duration-ms="0" started-at="2015-04-03T10:28:59Z" finished-at="2015-04-03T10:28:59Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[wrong number of arguments]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.afterRun(TestRunner.java:1014)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addScreenshot -->
        <test-method status="SKIP" signature="closeDriver()[pri:0, instance:services.vea.VeaBot@7e78fc6]" name="closeDriver" is-config="true" duration-ms="0" started-at="2015-04-03T10:28:59Z" finished-at="2015-04-03T10:28:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- services.vea.VeaBot -->
    </test> <!-- Vea -->
  </suite> <!-- Vea -->
</testng-results>
